### ISSUE TITLE
Consider updating to material design

### ISSUE THREAD

**Issue by dan-l** [napon/VibrateTimer#12]

**Comment by napon** [comment]
Im thinking of changing the interface completely. Instead of a list view we
can instead display the timers on a one week calendar. Easier to add timers
and the overall design is more intuitive. Only problem is no time qq school
op

**Comment by dan-l** [comment]
^ nice one. 
I will be willing to do it. Motivation is running high :+1:

**Comment by napon** [comment]
Sure lets work on it soon! (Prob after 304 midterm lolol)

**Comment by dan-l** [comment]
#13

**Comment by ameliayap** [comment]
o.O much commitment xD if u need help i can help too hehe no school == more free time ^_^
